### ISSUE TITLE
Cannot select all text

### ISSUE THREAD

**Issue by assembledadam** [carbon-tools/carbon#80]
Can only select text one paragraph at a time.

**Comment by mkhatib** [comment]
Not sure what do you mean here, how are you trying to select the text? `Ctrl/Cmd + A?` Or Click and Drag?

**Comment by assembledadam** [comment]
Apologies, I wasn't clear enough here.

Pressing Cmd + A works to select all text.  However, dragging up or down only allows you to select a single paragraph. I can reproduce this on the demo using Chrome 50/Firefox/Opera on a Mac.

**Comment by assembledadam** [comment]
Did you manage to reproduce this?

The only way I've found to get around it (highlighting more than one paragraph at a time) is to do it via keyboard (shift with arrow keys).

**Comment by mkhatib** [comment]
Thanks for pinging back, yes was able to repro. And yeah I am too used to Shift+click to select big chunk of text almost never use the drag. Thanks for catching this.

I think this is due to the fact that each paragraph is its own `contenteditable` block so I think browsers stop the selection process when it hits the end of that contenteditable. This sucks, I know we did this change for better user experience but I can't remember exactly what was the problem before switching from a single `contenteditable` for all the editor. 

Will have to think some more about this. But one way to "fix" this is to do our own tracking of the mouse cursor and update selection as user is moving - this probably would totally suck and want to avoid this.
