### ISSUE TITLE
Bug & Feature request: deleting embeds is clumsy

### ISSUE THREAD

**Issue by assembledadam** [carbon-tools/carbon#89]
Deleting embeds is a bit of a nightmare in its current form, and results in a frustrating user experience.
1. Right now it seems the only way to delete an embed is to ensure your cursor is on a paragraph of text after the embed, and then hitting backspace.  At least that's how it used to work, although I think the fix to #85 may have stopped this working?  It doesn't work locally or on the demo for me anymore (Mac, Chrome 50).
2. Backspace is the key for most browser to go 'back'.  So when this doesn't work for any reason, the whole browser directs you to the previous page without the user intending it. 
3. If there is no paragraph of text after the embed (i.e. an embed followed by another embed), it seems impossible to delete the embed.

I think the most intuitive way to delete an embed would be:
- (Best option in my opinion) Allow the user to highlight the embed by either hitting backspace from the paragraph after it, or with their mouse, and capture a delete or backspace keypress to remove it (see medium.com for an example of this).
- Place a 'remove' button somewhere on the embed or align toolbar

**Comment by mkhatib** [comment]
I might have introduced this in #85 as you mentioned, will work on this asap. Deleting embeds should work as you described by backspacing into it from a next paragraph, or deleting from a previous paragraph or by clicking on it to selecting.

> Backspace is the key for most browser to go 'back'. So when this doesn't work for any reason, the whole browser directs you to the previous page without the user intending it.

Luckily at least for Chrome this is changing and they're dropping backspace for back.

> Place a 'remove' button somewhere on the embed or align toolbar

Can you file a separate bug for this, agreed this is specially needed on mobile.

**Comment by assembledadam** [comment]
I'm fairly sure than even before #85 you were not able to select the embed and remove it with backspace - at least not in Chrome anyway - you had to select the text after it and then hit backspace until it selected it and then removed it. I will double check this tomorrow.

I think having that work + the capturing presses of the delete key when an embed is selected would be the most intuitive (as Medium does it). For mobile, as you say a button may be best, but there are some other fundamental issues I would say need to be addressed before this if mobile is a consideration (such as the inability to format text at the moment).

I'm actually just going to disable mobile editing in my app for now as it's a little bit of a minefield with contenteditable. I understand that Medium requires a native app for mobile editing for this very reason.

Certain open to giving it a go though.

**Comment by assembledadam** [comment]
Regarding the backspace, it's also the shortcut for 'back' in Firefox and I believe IE (not sure about Edge).  So I think this adds more weight to the argument for adding the delete key as an option for deleting embeds (to be sure you just delete and not run the risk of accidentally going back).

I got around this potential hazard on my app by capturing edits and offering an 'are you sure' dialog, but it certainly isn't ideal.

**Comment by mkhatib** [comment]
> I'm fairly sure than even before #85 you were not able to select the embed and remove it with backspace - at least not in Chrome anyway - you had to select the text after it and then hit backspace until it selected it and then removed it. I will double check this tomorrow.

```
paragraph 1
image
paragraph 2
embed
header
```

Please do. This is how I am handling it now, and just tested it and works. For the example above.
- Cursor at the beginning of `header`
- User hits backspace
- `embed` is selected
- User hits backspace again
- `embed` is deleted and cursor moves to end of `paragraph 2`

If you're not seeing the behavior above, please let me know. If you think this behavior should change let me know because as you describe it, it sounds like this is the behavior you're looking for unless I am missing something. Delete works very similar to this with the opposite directions.

> I'm actually just going to disable mobile editing in my app for now as it's a little bit of a minefield with contenteditable. I understand that Medium requires a native app for mobile editing for this very reason.

Mobile editing actually works OK now in Carbon - it used to be much worst 😄 but since we moved to `input` event handling it's a bit better - it definitely needs more refinement and lots testing there but I tested it out on mobile and it "works".

> but there are some other fundamental issues I would say need to be addressed before this if mobile is a consideration (such as the inability to format text at the moment).

I could swear this used to work on mobile but just tested this and it doesn't seem it triggers the formatting bar - my guess selection events are not being fired - will have to look into this but thanks for bringing that to my attention - will file a bug - please feel free to file bugs against mobile as well - would love to get it work really well on mobile - it's doable but needs lots of work. 

Also consider allowing mobile editing behind a warning screen, "Editing on mobile is not yet fully supported and might cause headache and loss of text - are you sure you'd like to continue?" or something more scarier 💀 .

Also just tested out deleting embeds and images on mobile - works pretty well with the virtual keyboard "backspace" key - though I have a bug to disable showing the keyboard when embeds are selected on mobile - #70 - so still think we need that delete button at some point.

> I got around this potential hazard on my app by capturing edits and offering an 'are you sure' dialog, but it certainly isn't ideal.

This is definitely how I would implement this, I don't think this should be part of the editor, but the problem with `backspace` is definitely worth looking into some more.
